# Generated by Django 5.2.1 on 2025-05-18 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
